import os
from utils.del_dir import delete_recursive

import config as c

def build_new(datapack_name):
    if c.rebuild_datapack_if_exists:
        delete_recursive(datapack_name)

    function_list =  c.playsound_command_list()
    assert len(function_list) == 75
    
    if os.path.exists(datapack_name):
        return function_list

    os.mkdir(datapack_name)
    metadata = '''{
    "pack": {
        "pack_format": 6,
        "description": "Auto-generated by SimpleRedstoneGenerator"
    }
}
'''
    with open(os.path.join(datapack_name, 'pack.mcmeta'), "w") as f:
        f.write(metadata)
    
    dir_func = os.path.join(datapack_name, 'data')
    os.mkdir(dir_func)
    dir_func = os.path.join(dir_func, 'rmgen')
    os.mkdir(dir_func)
    dir_func = os.path.join(dir_func, 'functions')
    os.mkdir(dir_func)


    for key_id, value in enumerate(function_list):
        key = f'key{key_id + 9}'
        for delay in range(3):
            loc = 1 - delay if delay == 0 else -delay
            function_command = '''execute run summon minecraft:falling_block 1 ~%d ~ {DropItem:false,Time:1,BlockState:{Name:"glowstone"}}
    summon minecraft:falling_block ~%d ~%d ~ {DropItem:false,Time:1,BlockState:{Name:"command_block"},TileEntityData:{auto:true,Command:"stopsound @a record %s"}}
    summon minecraft:falling_block ~%d ~%d ~ {DropItem:false,Time:1,BlockState:{Name:"command_block"},TileEntityData:{auto:true,Command:"execute at @a run playsound %s record @p ~ ~ ~ 999"}}
    summon minecraft:falling_block ~%d ~%d ~ {DropItem:false,Time:1,BlockState:{Name:"command_block"},TileEntityData:{auto:true,Command:"fill ~ ~ ~ ~-2 ~ ~ air"}}
    '''%(20+delay, loc,20+delay, value, 1+loc ,20+delay, value, 2+loc, 20+delay)
            with open(os.path.join(dir_func, f'{key}play_d{delay}.mcfunction'), "w") as f:
                f.write(function_command)
        function_command = '''execute run summon minecraft:falling_block ~1 ~20 ~ {DropItem:false,Time:1,BlockState:{Name:"command_block"},TileEntityData:{auto:true,Command:"stopsound @a record %s"}}
summon minecraft:falling_block ~2 ~20 ~ {DropItem:false,Time:1,BlockState:{Name:"command_block"},TileEntityData:{auto:true,Command:"fill ~ ~ ~ ~-1 ~ ~ air"}}
'''%(value)
        with open(os.path.join(dir_func, key+'stop.mcfunction'), "w") as f:
            f.write(function_command)
    return function_list